spring:
  application:
    name: distributed-key-vault

server:
  port: ${SERVER_PORT:8080}

node:
  node-id: ${NODE_ID:node-1}
  all-nodes:
    - id: node-1
      url: http://localhost:8080
    - id: node-2
      url: http://localhost:8081
    - id: node-3
      url: http://localhost:8082
